drf_test/urls.py
from django.urls import path
from . import views
from knox import views as knox_views

app_name = "drf_test"

urlpatterns = [
    
    
    path('Auther_viewset/',views.Auther_viewset.as_view({'get':'list','post':'create'})),
    path('Auther_viewset/<id>',views.Auther_viewset.as_view({'get':'retrieve','put':'update',})),
    path('Auther_viewset/<id>',views.Auther_viewset.as_view({'delete':'destroy'})),



    


    
    path('Books_viewset/',views.Books_viewset.as_view({'get':'list','post':'create'})),
    path('Books_viewset/<id>',views.Books_viewset.as_view({'get':'retrieve','put':'update','delete':'destroy'})),




]

employee/urls.py
from django.urls import path
from . import views
from knox import views as knox_views

app_name = "employee"

urlpatterns = [
    
    path('login_viewset/',views.login_viewset.as_view()), 

    path('LogoutView/',knox_views.LogoutView.as_view()),

    path('Employee_viewset/',views.Employee_viewset.as_view({'get':'list','post':'create'})),

    path('Designation_viewset/',views.Designation_viewset.as_view({'get':'list','post':'create'})),

    path('Department_viewset/',views.Department_viewset.as_view({'get':'list','post':'create'})),

    path('Leave_type_viewset/',views.Leave_type_viewset.as_view({'get':'list','post':'create'})),

    path('Leave_viewset/',views.Leave_viewset.as_view({'get':'list','post':'create','delete':'destroy'})),   

    path('attendence_viewset/',views.Attendence_viewset.as_view({'get':'list','post':'create'})), 

    path('approved_reject_viewset/<id>',views.Approved_reject_viewset.as_view({'get':'retrieve','patch':'update'})),

    path('Punch_in_out_viewset/',views.Punch_in_out_viewset.as_view({'post':'create'})), 

    path('Change_password_viewset/',views.Change_password_viewset.as_view({'post':'update','get':'list'})),  



]

employee_ess/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('', include('drf_test.urls')),

    path('api-auth/', include('rest_framework.urls')),
]

employee/models.py
from django.contrib.auth.models import AbstractUser,AbstractBaseUser
from django.db import models 


class designation(models.Model):
    designation_name = models.CharField(max_length=100)

    def __str__(self):
        return self.designation_name
    
class department(models.Model):
    department_name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)

    def __str__(self):
        return self.department_name

class Employee(AbstractUser):
    username =  models.CharField(max_length=250,blank=True,null=True,unique=True)
    first_name =  models.CharField(max_length=250,blank=True,null=True)
    last_name =  models.CharField(max_length=250,blank=True,null=True)
    email = models.EmailField(blank=True)
    dob = models.DateField(blank=True,null=True)
    address = models.CharField(max_length=250,blank=True,null=True)
    phone_no = models.BigIntegerField(blank=True,null=True)
    email = models.EmailField(blank=True,null=True,unique=True)
    password = models.CharField(max_length=12)
    employee_designation = models.ForeignKey(designation,on_delete=models.CASCADE,blank=True,null=True,)
    employee_department = models.ForeignKey(department,on_delete=models.CASCADE,blank=True,null=True,related_name="department_hit")
    access_status = (
        ('A','Admin'),
        ('E','Employee')
    )
    acess_type = models.CharField(max_length=20,choices=access_status,blank=True,null=True)

    
    
    def __str__(self):
        return self.first_name

class leave_type(models.Model):
    leave_name = models.CharField(max_length=100)
    max_leaves = models.IntegerField()
    CARRY_STATUS = (
        ('Yes','Yes'),
        ('No','No')
    ) 
    carry_forword = models.CharField(max_length=20,choices=CARRY_STATUS)

    def __str__(self):
        return self.leave_name

class leave(models.Model):
    employee_name = models.ForeignKey(Employee,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    leave_types = models.ForeignKey(leave_type,on_delete=models.CASCADE)
    LEAVE_STATUS = (
        ('Approved','Approved'),
        ('Rejected','Rejected')
    ) 
    status = models.CharField(max_length=20,choices=LEAVE_STATUS,blank=True,null=True)
    A_R_date  = models.DateField(blank=True,null=True)

    # def __str__(self):
    #     return self.employee_name.first_name
    


class attendence(models.Model):
    employee_name =  models.ForeignKey(Employee,on_delete=models.CASCADE,blank=True,null=True)
    punch_in = models.DateTimeField(null=True,blank=True)
    punch_out = models.DateTimeField(null=True,blank=True)
    date =  models.DateField()
    duration = models.CharField(max_length=200,blank=True,null=True,default=0)

    
    

employee/views.py
from datetime import date, datetime
from pytz import timezone
from django.shortcuts import render,redirect
from .models import  department, designation,leave_type,leave,attendence
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login,logout
from django.contrib import messages 
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Employee
from rest_framework import filters

# -------------------------API--------------------------------
from employee.serializers import (Empoloyee_Serializer,Designation_Serializer,Department_Serializer,Leave_type_Serializer,
                                Leave_Serializer,Attendence_Serializer,Approved_reject_Serializer,Punch_in_out_Serializer,
                                Change_password_Serializer
                                )
from rest_framework.response import Response
from rest_framework.authtoken.serializers import AuthTokenSerializer
from rest_framework import viewsets
from rest_framework import permissions
from knox.views import LoginView as KnoxLoginView
from knox.auth import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from rest_framework import status
from django_filters.rest_framework import DjangoFilterBackend

# -------------------------API Class----------------------------
class login_viewset(KnoxLoginView):
    permission_classes = (permissions.AllowAny,)
    def post(self, request):
            print("Login-----------------------------",self)
            print('request.data---------------------------',request.data)
            serializer = AuthTokenSerializer(data = request.data)
            serializer.is_valid()
            user = serializer.validated_data['user']
            login(request,user)
            list = super(login_viewset,self).post(request)
            print("Token---------------------------------------",  list.data)

            list.data['Username'] = user.first_name
            list.data['Email'] = user.email

            return Response(list.data)
    
class Employee_viewset(viewsets.ModelViewSet):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    serializer_class = Empoloyee_Serializer
    queryset =  Employee.objects.all()
    filter_backends = [filters.SearchFilter]
    search_fields = ['^username','email']
    filter_backends = [filters.OrderingFilter]
    ordering_fields = ['email']
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['username']
    

    def create(self, request, *args, **kwargs):
        data = request.data
        print(data,'=============================')
        users = Employee.objects.create(username=data['username'],first_name=data['first_name'],last_name=data['last_name'],
                                        email=data['email'],dob=data['dob'],address=data['address'],phone_no=data['phone_no']
                                          ,employee_designation_id=data['employee_designation_id'],employee_department_id=
                                          data['employee_department_id'],acess_type=data['acess_type'],
                                          )
        users.password=make_password(password=data['password'])
        users.save()
        serializer = self.serializer_class(users)
        return Response(serializer.data)       

class Designation_viewset(viewsets.ModelViewSet):       
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Designation_Serializer
    queryset =  designation.objects.all()

class Department_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Department_Serializer
    queryset =  department.objects.all()

class Leave_type_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Leave_type_Serializer
    queryset =  leave_type.objects.all()      

class Leave_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Leave_Serializer
    lookup_field ="id"
    queryset =  leave.objects.all()      

class Attendence_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Attendence_Serializer
    queryset =  attendence.objects.all()     

class Approved_reject_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Approved_reject_Serializer
    lookup_field ="id"

    def retrieve(self, request, *args, **kwargs):
        id = kwargs['id']
        queryset =  leave.objects.get(employee_name__id=self.kwargs['id'])
        serializer = Approved_reject_Serializer(queryset)
        return Response(serializer.data)
    
    def update(self, request, *args, **kwargs):
        if request.data['status'] == 'Approved':
            print('----------------------',request.data,self.kwargs['id'])
            statu = leave.objects.get(employee_name__id=self.kwargs['id'])
            statu.status = 'Approved successfully'
            statu.A_R_date=date.today()
            statu.save()
            return Response(data={'success'})
        

        if request.data['status'] == 'Rejected':
            print('----------------------',request.data)
            status = leave.objects.filter(employee_name__id=self.kwargs['id']).update(
            status = 'Rejected')
            return Response(data={'Rejected successfully'})
    
class Punch_in_out_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Punch_in_out_Serializer
    queryset =  attendence.objects.all() 

    def create(self, request, *args, **kwargs):
        if request.data['status'] == 'punchin':
            status = attendence.objects.create(
                employee_name_id=request.user.id,date = date.today(),
                punch_in=datetime.now(timezone("Asia/Kolkata")))
            return Response(data={'punch-in successfully'})
        if request.data['status'] == 'punchout':
            status = attendence.objects.get(employee_name_id=request.user.id,punch_out=None)
            status.punch_out = datetime.now(timezone("Asia/Kolkata"))
            status.date = date.today()
            print(status.punch_out , status.punch_in,'=================================')
            print(status.punch_out-status.punch_in,'=================================')

            status.duration = status.punch_out - status.punch_in
            status.save()
            return Response(data={'punch-out successfully'})
    
    
class Change_password_viewset(viewsets.ModelViewSet):
    authentication_classes = (TokenAuthentication,)
    permission_classes = (IsAuthenticated,)
    serializer_class = Change_password_Serializer
    queryset =  Employee.objects.all() 

    def update(self, request, *args, **kwargs):
        oldpassword = request.data['oldpassword']
        newpassword = request.data['newpassword']
        confirmpassword = request.data['confirmpassword']
        user = Employee.objects.get(email=request.user.email)
        if not user.check_password(oldpassword):
            return Response({"message":"old password is not correct"},status=status.HTTP_200_OK)
        else:
            if newpassword==confirmpassword:
                user = Employee.objects.get(id=request.user.id)
                user.password = make_password(password=confirmpassword)
                user.save()
                return Response({"message":"change password sucessfully"},status=status.HTTP_200_OK)
            else:
                return Response({"error":"newpassword and confirmpassword are not same"},status=status.HTTP_400_BAD_REQUEST)
        






    

templates/employee folder/employee_form.html
{%extends 'base.html'%}
{%block content%}
<!-- 
{%for message in messages%}
<div class="alert alert-danger alert-dismissible fade show" role="alert"><button type="button" class="btn-close"
    data-bs-dismiss="alert"></button>
    {{message}}
</div>
{%endfor%} -->
</br>
<a href="{%url 'employee:useremployee_list'%}" class="btn btn-primary" style="margin:0% 0% 0% 95%;">Back</a></br></br>
<div>
    <center>
        <h2 class="alert alert-info"><u>EMPLOYEE FORM</u></h2>
    </center><br>
    <form method="post" action="/useremployee_form/">
        {% csrf_token %}

        <div class="container col-5">
            <div class="row">
                <div class="mb-3 ">
                    <label for="firstname" class="form-label" style="color: rgb(18, 20, 22);"><b>firstname:</b></label>
                    <input type="text" class="form-control" id="firstname" name="firstname"
                        placeholder="Enter Firstname">

                </div>

                <div class="mb-3">
                    <label for="lastname" class="form-label" style="color: rgb(18, 20, 22);"><b>lastname:</b></label>
                    <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Enter Lastname">

                </div>
                <div class="mb-3">
                    <label for="date" class="form-label" style="color: rgb(18, 20, 22);"><b>DOB:</b></label>
                    <input type="date" class="form-control" id="dob" name="dob" placeholder="Enter Date Of Birth">

                </div>
                <div class="mb-3">
                    <label for="adress" class="form-label" style="color: rgb(18, 20, 22);"><b>Adress:</b></label>
                    <textarea class="form-control" id="adress" name="adress" placeholder="Enter Adress"></textarea>


                    <div class="mb-3">
                        <label for="email" class="form-label" style="color: rgb(18, 20, 22);"><b>email:</b></label>
                        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">

                    </div>

                </div>
                <div class="mb-3">
                    <label for="phoneno" class="form-label" style="color: rgb(18, 20, 22);"><b>Phone no:</b></label>
                    <input type="text" class="form-control" id="phone" name="phone" placeholder="Enter Phone no">

                </div>


                <div class="mb-3 ">
                    <label for="password" class="form-label" style="color: rgb(18, 20, 22);"><b>password:</b></label>
                    <input type="password" class="form-control" id="password" name="password"
                        placeholder="Enter Password">

                </div>

                <div class="mb-3 ">
                    <label for="designation" class="form-label" style="color: rgb(18, 20, 22);"><b>Employee
                            Designation:</b></label>
                    <select name="designation" id="designation" class="form-control">
                        {%for i in designation_var%}
                        <option value="{{i.designation_name}}">{{i.designation_name}}</option>
                        {%endfor%}
                    </select>
                </div>

                <div class="mb-3 ">
                    <label for="designation" class="form-label" style="color: rgb(18, 20, 22);"><b>Employee
                            Department:</b></label>
                    <select name="department" id="department" class="form-control" >
                        {%for i in department_var%}
                        <option value="{{i.department_name}}">{{i.department_name}}</option>
                        {%endfor%}
                    </select>
                </div>
                <div class="mb-3 ">
                    <label for="access_type" class="form-label" style="color: rgb(18, 20, 22);"><b>Access
                            Type:</b></label></br>
                    <input type="radio" id="Admin" name="access_type" value="Admin">
                    <label for="access_type" class="form-label" style="color: rgb(18, 20, 22);">Admin</label>
                    <input type="radio" id="Employee" name="access_type" value="Employee">
                    <label for="access_type" class="form-label" style="color: rgb(18, 20, 22);">Employee</label>
                </div>

                <div class="mb-3 ">
                    <label for="designation" class="form-label" style="color: rgb(18, 20, 22);"><b>Reporting
                            To:</b></label>
                    <select name="reporting" id="reporting" class="form-control" >
                        {%if first_name != null%}
                        {%for i in first_name%}
                        <option value="{{i.first_name}}">{{i.first_name}}</option>
                        {%endfor%}
                        {%endif%}
                        <option value="None">None</option>
                    </select>
                </div>


            </div>


        </div>


</div>

</div>

<center> <button type="submit" class="btn btn-primary">Submit</button></center>
{{data}}
</form>
</br></br></br>



{%endblock%}

templates/employee folder/employee_list.html
{%extends 'base.html'%}
{%block content%}

<head>
  <style>
    table {
      font-family: arial, sans-serif; 
      border-collapse: collapse;
      width: 100%;
    }

    td,
    th {
      text-align: left;
      padding: 8px;
      color: rgb(1, 1, 14);
      font-size: large;
    }

    .list {
      background-image: url('/static/image/dark2.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    table, th, td {
  border: 1px solid white;        
  border-collapse: collapse;
}
th, td {
  background-color: #99cdf0;
}
  </style>
</head>

<body class="list">
</br>
{% if user.is_superuser %}
<a href="{%url 'employee:useremployee_form'%}" class="btn btn-primary" style="margin:0% 0% 0% 90%;">+Add Employee</a></br></br>
{%endif%}
    <center>
        <h2 class="alert alert-danger"><u>EMPLOYEE LIST</u></h2>
    </center><br>
    <div class="col-sm-4-COL-56" style="margin-left:0%;">
  
  <table>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Dob</th>
      <th>Address</th>
      <th>Phone no</th>
      <th>Email</th>
      <th>Employee designation</th>
      <th>Employee department</th>
      <th>Access type</th>
      <th>Reporting to</th>

    </tr>
    
    <tr>
      {%for e_list in data%}
      <td>{{forloop.counter}}</td>
      <td>{{e_list.first_name}} {{e_list.last_name}}</td>
      <td>{{e_list.dob}}</td>
      <td>{{e_list.address}}</td>
      <td>{{e_list.phone_no}}</td>
      <td>{{e_list.email}}</td>
      <td>{{e_list.employee_designation}}</td>
      <td>{{e_list.employee_department}}</td>
      <td>{{e_list.get_acess_type_display}}</td>
      <td>{{e_list.reporting_to.first_name}}</td>
    </tr>
    {% endfor %}
  
  </table>
  </div>
  <br />
</body>
{%endblock%}