drf_test/urls.py
from django.urls import path
from . import views
from knox import views as knox_views

app_name = "drf_test"

urlpatterns = [
    
    
    path('Auther_viewset/',views.Auther_viewset.as_view({'get':'list','post':'create'})),
    path('Auther_viewset/<id>',views.Auther_viewset.as_view({'get':'retrieve','put':'update',})),
    path('Auther_viewset/<id>',views.Auther_viewset.as_view({'delete':'destroy'})),



    


    
    path('Books_viewset/',views.Books_viewset.as_view({'get':'list','post':'create'})),
    path('Books_viewset/<id>',views.Books_viewset.as_view({'get':'retrieve','put':'update','delete':'destroy'})),




]

employee_ess/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employee.urls')),
    path('', include('drf_test.urls')),

    path('api-auth/', include('rest_framework.urls')),
]

employee/models.py
from django.contrib.auth.models import AbstractUser,AbstractBaseUser
from django.db import models 


class designation(models.Model):
    designation_name = models.CharField(max_length=100)

    def __str__(self):
        return self.designation_name
    
class department(models.Model):
    department_name = models.CharField(max_length=100)
    code = models.CharField(max_length=100)

    def __str__(self):
        return self.department_name

class Employee(AbstractUser):
    username =  models.CharField(max_length=250,blank=True,null=True,unique=True)
    first_name =  models.CharField(max_length=250,blank=True,null=True)
    last_name =  models.CharField(max_length=250,blank=True,null=True)
    email = models.EmailField(blank=True)
    dob = models.DateField(blank=True,null=True)
    address = models.CharField(max_length=250,blank=True,null=True)
    phone_no = models.BigIntegerField(blank=True,null=True)
    email = models.EmailField(blank=True,null=True,unique=True)
    password = models.CharField(max_length=12)
    employee_designation = models.ForeignKey(designation,on_delete=models.CASCADE,blank=True,null=True,)
    employee_department = models.ForeignKey(department,on_delete=models.CASCADE,blank=True,null=True,related_name="department_hit")
    access_status = (
        ('A','Admin'),
        ('E','Employee')
    )
    acess_type = models.CharField(max_length=20,choices=access_status,blank=True,null=True)

    
    
    def __str__(self):
        return self.first_name

class leave_type(models.Model):
    leave_name = models.CharField(max_length=100)
    max_leaves = models.IntegerField()
    CARRY_STATUS = (
        ('Yes','Yes'),
        ('No','No')
    ) 
    carry_forword = models.CharField(max_length=20,choices=CARRY_STATUS)

    def __str__(self):
        return self.leave_name

class leave(models.Model):
    employee_name = models.ForeignKey(Employee,on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    leave_types = models.ForeignKey(leave_type,on_delete=models.CASCADE)
    LEAVE_STATUS = (
        ('Approved','Approved'),
        ('Rejected','Rejected')
    ) 
    status = models.CharField(max_length=20,choices=LEAVE_STATUS,blank=True,null=True)
    A_R_date  = models.DateField(blank=True,null=True)

    # def __str__(self):
    #     return self.employee_name.first_name
    


class attendence(models.Model):
    employee_name =  models.ForeignKey(Employee,on_delete=models.CASCADE,blank=True,null=True)
    punch_in = models.DateTimeField(null=True,blank=True)
    punch_out = models.DateTimeField(null=True,blank=True)
    date =  models.DateField()
    duration = models.CharField(max_length=200,blank=True,null=True,default=0)

    
    

templates/leave_type folder/leave_type.html
{%extends 'base.html'%}
{%block content%}
<!-- 
{%for message in messages%}
<div class="alert alert-danger alert-dismissible fade show" role="alert"><button type="button" class="btn-close"
    data-bs-dismiss="alert"></button>
    {{message}}
</div>
{%endfor%} -->
</br>
<a href="{%url 'employee:userleave_type_list'%}" class="btn btn-primary" style="margin:0% 0% 0% 95%;">Back</a></br></br>
<div>
    <center>
        <h2 class="alert alert-info"><u>LEAVE TYPE FORM</u></h2>
    </center><br>
    <form method="post" action="/userleave_type/">
        {% csrf_token %}
        <div class="container col-5">
            <div class="row">

                <div class="mb-3 ">
                    <label for="leave name" class="form-label"style="color: rgb(18, 20, 22);"><b>Leave Name:</b></label>
                    <input type="text" class="form-control" id="Leave_Name" name="Leave_Name"placeholder="Enter Leave Name" >

                </div>
                <div class="mb-3 ">
                    <label for="leave name" class="form-label"style="color: rgb(18, 20, 22);"><b>Max Leaves:</b></label>
                    <input type="number" class="form-control" id="Max_Leaves" name="Max_Leaves"placeholder="Enter Max Leaves" >
                </div>
                <div class="mb-3 ">
                    <label for="Carry_Forword" class="form-label"style="color: rgb(18, 20, 22);"><b>Carry   :</b></label></br>
                    <input type="radio" id="yes" name="Carry_Forword" value="yes">
                    <label for="Carry_Forword" class="form-label"style="color: rgb(18, 20, 22);">Yes</label>
                    <input type="radio" id="no" name="Carry_Forword" value="no">
                    <label for="Carry_Forword" class="form-label"style="color: rgb(18, 20, 22);">No</label>
                </div>     
        </div>


        <center> <button type="submit" class="btn btn-primary">Submit</button></center>
</div>

</form>
</div>
{%endblock%}

templates/leave_type folder/leave_type_list.html
{%extends 'base.html'%}
{%block content%}

<head>
  <style>
    table {
      font-family: arial, sans-serif; 
      border-collapse: collapse;
      width: 100%;
    }

    td,
    th {
      text-align: left;
      padding: 8px;
      color: rgb(1, 1, 14);
      font-size: large;
    }

    .list {
      background-image: url('/static/image/dark2.webp');
      background-repeat: no-repeat;
      background-attachment: fixed;
      background-size: cover;
    }
    table, th, td {
  border: 1px solid white;        
  border-collapse: collapse;
}
th, td {
  background-color: #99cdf0;
}
  </style>
</head>

<body class="list">
</br>
<a href="{%url 'employee:userleave_type'%}" class="btn btn-primary" style="margin:0% 0% 0% 90%;">+Add Leave Type</a></br></br>

    <center>
        <h2 class="alert alert-danger"><u>LEAVE TYPE LIST</u></h2>
    </center><br>
    <div class="col-sm-4" style="margin-left:35%;">
  <table>
    <tr>
      <th>No.</th>
      <th>Leave Name</th>
      <th>Max Leaves</th>
      <th>Carry Forword</th>
    </tr>

    {%for e_type_list in data%}
    <tr>
      <td>{{forloop.counter}}</td>
      <td>{{e_type_list.leave_name}}</td>
      <td>{{e_type_list.max_leaves}}</td>
      <td>{{e_type_list.get_carry_forword_display}}</td>
    </tr> {%endfor%}

    
  
  </table>
  </div>
  <br />
</body>
{%endblock%}